version: '3.9'

services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    volumes:
      - ./Corefile:/Corefile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - dns-net

networks:
  dns-net:
    driver: bridge